### PR TITLE
Add Limit Props

### PR DESCRIPTION
**Pull request by pedroparra**
Allow by props, limit the tags added.

### CODE REVIEW

**Comment by pedroparra** [comment]
I forget to add to the props description  ( 0 = infinite )

**Comment by olahol** [comment]
Looks like a nice addition, but I'm thinking maybe -1 = infinite? That way people who want to completely disable inputting tags can do that.

**Comment by pedroparra** [comment]
OK, Fixed!

**Comment by olahol** [comment]
Quick work, I like it :smile:. Thanks for the contribution @pedroparra.

**Comment by pedroparra** [comment]
I needed this change for tomorrow :smile: . Thanks!

**Pull request merged**
