### PR TITLE
Restructure css and add tag themes

### PR DESCRIPTION
**Pull request by gauravtiwari**
Hey @olahol 

Sort of cosmetic change, I had couple of tag stylings done so, I thought may be it would be good to put some standard tag themes - red, blue, grey etc. 

I have basically, restructured the default demo css and moved any tag styling to separate themes file (red, blue etc). I was thinking to may be use Material style input styling, probably in next commit. 

Adding a few screenshots for demo. Please review and merge, if appropriate.

Gaurav

grey-theme
red theme

### CODE REVIEW

**Comment by olahol** [comment]
Hello @gauravtiwari

Wow, this looks really nice! 

I was wondering if you could add some of the styles to the files `examples/`, I was having a little trouble getting them right.

 I was also wondering if they could be made a little more generic by removing `width` and `height` css attributes?

Ola

**Comment by gauravtiwari** [comment]
Sure @olahol Yup I will cleanup width and height. It's actually an extraction from an existing project. I will add examples as well.

**Comment by olahol** [comment]
Thank you @gauravtiwari

**Comment by gauravtiwari** [comment]
@olahol - Pushed the changes and updated Readme. Please take a look at the example folder with two examples, it's pretty simple. To test multiple themes just change themes styles file in the head.

**Comment by olahol** [comment]
Nice work, I'm taking a look at it now.

**Comment by gauravtiwari** [comment]
BTW, this is where I used it (side project): https://pure-escarpment-4869.herokuapp.com/members?q=keyword:ola+location:sweden

**Comment by olahol** [comment]
That's a really cool project, you should make a post on Hacker News, it could be very useful for startups :smiley:

**Comment by gauravtiwari** [comment]
Thanks @olahol I will - just a couple of more filters to add and get a domain for this. You are second person who found this interesting (just shared with 3 in total). If you think it's helpful to anyone, please share.

**Pull request closed without merging**
